### ISSUE TITLE
Wokwi testing in offical Espressif template project

### ISSUE THREAD

**Issue by tomassebestik** [wokwi/wokwi-esp-test-template#1]
Hi @urish,

We had the idea to update official [Espressif GitHub testing template repo](https://github.com/espressif/gh-esp-test-template) for Wokwi testing. 

Currently, our template repo only includes hardware testing, but it would be more useful for people to have both options - real hardware and emulation. Additionally, having these examples together would help better understand the similarities and differences between both processes.

I started making some updates in the Espressif project, but @georgik pointed me to this fork and the fact that you have already addressed it here already so well. Really nice job!

If you agree, I would propose creating a pull request to our repository and merging your changes from this fork back to our repo (the Espressif repo already has the WOKWI token in secrets). I can then update the docs in a following PR to include Wokwi testing.

Let me know WDYT. T

**Comment by urish** [comment]
Hi @tomassebestik, sounds good! Do you need me to create the PR?

**Comment by tomassebestik** [comment]
@urish That would be great if you can create PR. Many thanks!

**Comment by urish** [comment]
There we go!
